### ISSUE TITLE
Reture request: Listen to IP

### ISSUE THREAD

**Issue by tone-milazzo** [crash1604/Spotifylookalike#1]
I'm likely to run an app like this remotely off my linux box while I'm working in Windows. My linux machine is at 10.20.30.50. When running with 
`python3 manage.py runserver 10.20.30.50:8000`
The server claimed, "Starting development server at http://10.20.30.50:8000/" but the functionality wasn’t there.

**Comment by crash1604** [comment]
Please head to settings.py and add  http://10.20.30.50:8000/ to the list of allowed hosts.
This should resolve the issue
thanks
